parameters:
    ddr_doctrine.listener.uuid.strategy: 'random'

services:

    ddr.doctrine.event.listener.uuid:
        class: Dontdrinkandroot\DoctrineBundle\Event\Listener\UuidEntityListener
        calls:
            - ['setStrategy', ['%ddr_doctrine.listener.uuid.strategy%']]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ddr.doctrine.event.listener.created:
        class: Dontdrinkandroot\DoctrineBundle\Event\Listener\CreatedEntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ddr.doctrine.event.listener.updated:
        class: Dontdrinkandroot\DoctrineBundle\Event\Listener\UpdatedEntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Dontdrinkandroot\Repository\TransactionManager:
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - ['setLogger', ['@logger']]

    ddr.doctrine.configuration.routing.entity_loader:
        class: Dontdrinkandroot\DoctrineBundle\Configuration\Routing\EntityLoader
        arguments:
            - '@kernel'
        tags:
            - { name: routing.loader }

    Dontdrinkandroot\DoctrineBundle\Command\GenerateUuidCommand:
        arguments:
            - '@ddr.doctrine.event.listener.uuid'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: 'console.command', command: 'ddr:doctrine:generate-uuid' }

    Dontdrinkandroot\DoctrineBundle\Command\RenderDbalDiagramCommand:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'console.command', command: 'ddr:doctrine:render-dbal-diagram' }

    Dontdrinkandroot\DoctrineBundle\Command\RenderOrmDiagramCommand:
        tags:
            - { name: 'console.command', command: 'ddr:doctrine:render-orm-diagram' }

    Dontdrinkandroot\DoctrineBundle\Command\SetUuidsCommand:
        arguments:
            - '@doctrine'
            - '@ddr.doctrine.event.listener.uuid'
        tags:
            - { name: 'console.command', command: 'ddr:doctrine:set-uuids' }
