parameters:
    ddr_doctrine.listener.uuid.strategy: 'random'

services:

    ddr.doctrine.event.listener.uuid:
        class: Dontdrinkandroot\DoctrineBundle\Event\Listener\UuidEntityListener
        calls:
            - ['setStrategy', ['%ddr_doctrine.listener.uuid.strategy%']]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ddr.doctrine.event.listener.created:
        class: Dontdrinkandroot\DoctrineBundle\Event\Listener\CreatedEntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ddr.doctrine.event.listener.updated:
        class: Dontdrinkandroot\DoctrineBundle\Event\Listener\UpdatedEntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    ddr.doctrine.transaction_manager:
        class: Dontdrinkandroot\Repository\TransactionManager
        arguments:
            - '@doctrine.orm.entity_manager'

    ddr.doctrine.configuration.routing.entity_loader:
        class: Dontdrinkandroot\DoctrineBundle\Configuration\Routing\EntityLoader
        arguments:
            - '@kernel'
        tags:
            - { name: routing.loader }
