services:
    ddr_doctrine.event.listener.kernel:
        class: Dontdrinkandroot\DoctrineBundle\Event\Listener\TransactionalKernelEventListener
        arguments:
            - '@Dontdrinkandroot\Repository\TransactionManager'
        calls:
            - ['setLogger', ['@logger']]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 2048 }
            - { name: kernel.event_listener, event: kernel.finish_request }
            - { name: kernel.event_listener, event: kernel.terminate }
            - { name: kernel.event_listener, event: kernel.exception }
            - { name: monolog.logger, channel: doctrine }
