parameters:

services:

    Dontdrinkandroot\DoctrineBundle\Service\TransactionManager\TransactionManagerRegistry:
        arguments:
            - '@doctrine'

    Dontdrinkandroot\DoctrineBundle\Command\RenderDbalDiagramCommand:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'console.command', command: 'ddr:doctrine:render-dbal-diagram' }

    Dontdrinkandroot\DoctrineBundle\Command\RenderOrmDiagramCommand:
        tags:
            - { name: 'console.command', command: 'ddr:doctrine:render-orm-diagram' }
