language: php

matrix:
    include:
        -   php: "7.4"
            env: dependencies=lowest
        -   php: "7.4"
            env: dependencies=highest

addons:
    sonarcloud:
        organization: "dontdrinkandroot"
        token: $SONAR_TOKEN

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - php -m
    - phpenv config-rm xdebug.ini
    - pecl install pcov
    - if [ -z "$dependencies" ]; then COMPOSER_MEMORY_LIMIT=-1 composer install; fi;
    - if [ "$dependencies" = "lowest" ]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-lowest -n; fi;
    - if [ "$dependencies" = "highest" ]; then COMPOSER_MEMORY_LIMIT=-1 composer update -n; fi;
    - composer install

script:
    - php -d pcov.enabled=1 vendor/bin/phpunit --coverage-clover=coverage.clover.xml --log-junit log.junit.xml
    - if [ "$dependencies" = "highest" ]; then sonar-scanner; fi;
