language: php

matrix:
    include:
        -   php: "7.4"
            env: dependencies=lowest
        -   php: "7.4"
            env: dependencies=highest

addons:
    sonarcloud:
        organization: "dontdrinkandroot"
        token: $SONAR_TOKEN

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - phpenv config-rm xdebug.ini
    - if [ "$dependencies" = "lowest" ]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-lowest -n; fi;
    - if [ "$dependencies" = "highest" ]; then pecl install pcov; fi;
    - if [ "$dependencies" = "highest" ]; then COMPOSER_MEMORY_LIMIT=-1 composer update -n; fi;

script:
    - if [ "$dependencies" = "lowest" ]; then vendor/bin/phpunit; fi;
    - if [ "$dependencies" = "highest" ]; then php -d pcov.enabled=1 vendor/bin/phpunit --coverage-clover=coverage.clover.xml --log-junit log.junit.xml; fi;
    - if [ "$dependencies" = "highest" ]; then sonar-scanner; fi;
