<?php

namespace Dontdrinkandroot\DoctrineBundle\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

trait GeneratedIdEntityTrait
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT, nullable: false, options: ["unsigned" => true])]
    protected ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @internal IDs are autogenerated. Use only in tests.
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    public function isPersisted(): bool
    {
        return null !== $this->getId();
    }
}
